name: Deploy Nuxt to Dev

on:
  push:
    branches:
      - nuxt 
  pull_request:
    branches:
      - nuxt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' 

    - name: Install dependencies
      run: npm install

    - name: Build the Nuxt App
      run: npm run build